"Constants."

import string

VERSION = (0, 0, 1)
__version__ = ".".join([str(n) for n in VERSION])

EM_DASH = "\u2014"

SAFE_CHARACTERS = set(string.ascii_letters + string.digits)

DATETIME_ISOFORMAT = "%Y-%m-%d %H:%M:%S"

FOOTNOTES_EACH_TEXT = "after each text"
FOOTNOTES_EACH_CHAPTER = "after each chapter"
FOOTNOTES_END_OF_BOOK = "at end of book"

MAX_LEVEL = 6

DOCX_MAX_PAGE_BREAK_LEVEL = 4
DOCX_MAX_TOC_LEVEL = 4
DOCX_TOC_INDENT = 15
DOCX_TOC_SPACE_BEFORE = 0
DOCX_TOC_SPACE_AFTER = 0
DOCX_NORMAL_FONT = "Arial"
DOCX_NORMAL_FONT_SIZE = 12
DOCX_NORMAL_LINE_SPACING = 17
DOCX_SYNOPSIS_INDENT = 16
DOCX_SYNOPSIS_LINE_SPACING = 15
DOCX_SYNOPSIS_SPACE_BEFORE = 10
DOCX_SYNOPSIS_SPACE_AFTER = 10
DOCX_QUOTE_INDENT = 16
DOCX_CODE_FONT = "Courier"
DOCX_CODE_FONT_SIZE = 11
DOCX_CODE_LINE_SPACING = 12
DOCX_CODE_INDENT = 10
DOCX_FOOTNOTE_INDENT = 15
DOCX_CAPTION_INDENT = 15
DOCX_REFERENCE_INDENT = 10
DOCX_METADATA_SPACER = 80
DOCX_INDEXED_INDENT = 15
DOCX_INDEXED_SPACE_AFTER = 8
DOCX_DEFAULT_IMAGE_SCALE_FACTOR = 0.6
DOCX_DEFAULT_PNG_RENDERING_FACTOR = 2.0

EN_GB = "en-GB"
EN_US = "en-US"
SV_SE = "sv-SE"

LEXICON = {
    SV_SE: {
        "created": "skapad",
        "modified": "ändrad",
    }
}
LEXICON[SV_SE].update(
    dict([(k.capitalize(), v.capitalize()) for k, v in LEXICON[SV_SE].items()])
)
